const Api = [
    {
        "nome": "Naruto Uzumaki",
        "clã": "Uzumaki",
        "jutsu_especial": "Rasengan",
        "dano_especial": 1000,
        "natureza_de_chacra": "Vento",
        "patente": "Hokage",
        "defesa": 900,
        "ataque": 950,
        "imagem": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdQ7F46LFoeih8tCeid4C86CMgy42fOLKoXg&usqp=CAU",
        "id": 1
    },
    {
        "nome": "Sasuke Uchiha",
        "clã": "Uchiha",
        "jutsu_especial": "Chidori",
        "dano_especial": 1100,
        "natureza_de_chacra": "Relâmpago",
        "patente": "Ninja Renegado",
        "defesa": 850,
        "ataque": 970,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fwww.looper.com%2Fimg%2Fgallery%2Fevery-power-sasuke-has-on-naruto-explained%2Fintro-1663193400.jpg&tbnid=kOvBIwBOQZsRHM&vet=12ahUKEwiFvfXg5ZaCAxXoR7gEHbS9Do0QMyhDegUIARCSAg..i&imgrefurl=https%3A%2F%2Fwww.looper.com%2F1009943%2Fevery-power-sasuke-has-on-naruto-explained%2F&docid=rpGwmAtjBqsSwM&w=780&h=438&q=sasuke%20uchiha&hl=pt-BR&ved=2ahUKEwiFvfXg5ZaCAxXoR7gEHbS9Do0QMyhDegUIARCSAg",
        "id": 2
    },
    {
        "nome": "Sakura Haruno",
        "clã": "Haruno",
        "jutsu_especial": "Byakugou",
        "dano_especial": 800,
        "natureza_de_chacra": "Água",
        "patente": "Chunin",
        "defesa": 750,
        "ataque": 700,
        "imagem": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdXyB8aw3qJdj56xUSuv7B3rJrKtBXNeh-Fg&usqp=CAU",
        "id": 3
    },
    {
        "nome": "Kakashi Hatake",
        "clã": "Hatake",
        "jutsu_especial": "Kamui",
        "dano_especial": 1200,
        "natureza_de_chacra": "Relâmpago",
        "patente": "Hokage",
        "defesa": 950,
        "ataque": 930,
        "imagem": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmaEWLacETUwuFe_wliFj7UNg5QP0YqsqqoA&usqp=CAU",
        "id": 4
    },
    {
        "nome": "Gaara",
        "clã": "Kazekage",
        "jutsu_especial": "Sabaku Kyu",
        "dano_especial": 1050,
        "natureza_de_chacra": "Terra",
        "patente": "Kazekage",
        "defesa": 980,
        "ataque": 900,
        "imagem": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6oyyeEkNYNaV9emI-jDZFkjmHW9UtzgSKjw&usqp=CAU",
        "id": 5
    },
    {
        "nome": "Jiraiya",
        "clã": "Sannin",
        "jutsu_especial": "Rasengan",
        "dano_especial": 1100,
        "natureza_de_chacra": "Água",
        "patente": "Sannin",
        "defesa": 920,
        "ataque": 950,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fkanto.legiaodosherois.com.br%2Fw750-h450-k1%2Fwp-content%2Fuploads%2F2021%2F02%2Flegiao_jnhcQRAHmVtP.jpg.webp&tbnid=J4zG7tc8WeJuvM&vet=12ahUKEwjbs8XH5ZaCAxVBtZUCHZS3CJ8QMygIegUIARCCAQ..i&imgrefurl=https%3A%2F%2Fwww.legiaodosherois.com.br%2Fquiz%2Fnaruto-jiraiya.html&docid=gTQKjng1jMB-TM&w=750&h=392&q=jiraya%20naruro&hl=pt-BR&ved=2ahUKEwjbs8XH5ZaCAxVBtZUCHZS3CJ8QMygIegUIARCCAQ",
        "id": 6
    },
    {
        "nome": "Hinata Hyuga",
        "clã": "Hyuga",
        "jutsu_especial": "Gentle Fist",
        "dano_especial": 950,
        "natureza_de_chacra": "Água",
        "patente": "Jonin",
        "defesa": 800,
        "ataque": 870,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fi0.wp.com%2Fborutoexplorer.com.br%2Fwp-content%2Fuploads%2F2020%2F08%2FWhatsApp-Image-2020-08-16-at-11.58.39.jpeg%3Fresize%3D800%252C450%26ssl%3D1&tbnid=1CExmRXaTZS89M&vet=12ahUKEwi4vdHe35aCAxWJQ7gEHcvRD9MQMygEegQIARB0..i&imgrefurl=https%3A%2F%2Fborutoexplorer.com.br%2Freview-hinata-hyuuga%2F&docid=GBLW4rSsHABnXM&w=800&h=450&q=hinata%20hyuga%20&hl=pt-BR&ved=2ahUKEwi4vdHe35aCAxWJQ7gEHcvRD9MQMygEegQIARB0",
        "id": 7
    },
    {
        "nome": "Shikamaru Nara",
        "clã": "Nara",
        "jutsu_especial": "Shadow Possession",
        "dano_especial": 850,
        "natureza_de_chacra": "Vento",
        "patente": "Jonin",
        "defesa": 800,
        "ataque": 820,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fcriticalhits.com.br%2Fwp-content%2Fuploads%2F2021%2F12%2FShikamaru-1.jpg&tbnid=v7_kLf6NTADoHM&vet=12ahUKEwi6uKL135aCAxXaq5UCHeg4CBQQMygHegQIARB9..i&imgrefurl=https%3A%2F%2Fcriticalhits.com.br%2Fanime%2Fquais-transformacoes-da-natureza-shikamaru-consegue-utilizar-em-naruto%2F&docid=9yH0EgzpTzVB7M&w=1259&h=716&q=shikamaru%20nara&hl=pt-BR&ved=2ahUKEwi6uKL135aCAxXaq5UCHeg4CBQQMygHegQIARB9",
        "id": 8
    },
    {
        "nome": "Rock Lee",
        "clã": "Konoha",
        "jutsu_especial": "Eight Gates",
        "dano_especial": 1100,
        "natureza_de_chacra": "Taijutsu",
        "patente": "Chunin",
        "defesa": 950,
        "ataque": 800,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Frevolucaonerd.com%2Fwordpress%2Fwp-content%2Ffiles%2Frevolucaonerd.com%2F2023%2F02%2Frock-lee-vs-gaara.webp&tbnid=t9whyLO2NhASsM&vet=12ahUKEwi-18WO4JaCAxXTp5UCHTdoB9cQMygEegQIARB3..i&imgrefurl=https%3A%2F%2Frevolucaonerd.com%2Fqual-ep-rock-lee-luta-com-gaara%2F&docid=3tmULd6tgywWdM&w=1200&h=800&q=rock%20lee&hl=pt-BR&ved=2ahUKEwi-18WO4JaCAxXTp5UCHTdoB9cQMygEegQIARB3",
        "id": 9
    },
    {
        "nome": "Might Guy",
        "clã": "Konoha",
        "jutsu_especial": "Eight Gates",
        "dano_especial": 1100,
        "natureza_de_chacra": "Taijutsu",
        "patente": "jounin",
        "defesa": 960,
        "ataque": 850,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fstatic.wikia.nocookie.net%2Fnaruto%2Fimages%2Fb%2Fb1%2FGuy_abre_o_Oitavo_Port%25C3%25A3o.PNG%2Frevision%2Flatest%3Fcb%3D20150709184147%26path-prefix%3Dpt-br&tbnid=8lQVf71KmAnDaM&vet=12ahUKEwicsPua4JaCAxUgqpUCHex6AyAQMygCegQIARBO..i&imgrefurl=https%3A%2F%2Fnaruto.fandom.com%2Fpt-br%2Fwiki%2FMight_Guy&docid=BI4RbYdYeLzrBM&w=1920&h=1080&q=Might%20Guy&hl=pt-BR&ved=2ahUKEwicsPua4JaCAxUgqpUCHex6AyAQMygCegQIARBO",
        "id": 10
    },
    {
        "nome": "Tenten",
        "clã": "Não tem",
        "jutsu_especial": "Weapon Summoning",
        "dano_especial": 950,
        "natureza_de_chacra": "Fogo",
        "patente": "Jonin",
        "defesa": 870,
        "ataque": 820,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fcriticalhits.com.br%2Fwp-content%2Fuploads%2F2021%2F11%2F10-perguntas-fatos-e-curiosidades-sobre-Tenten-1.jpg&tbnid=V8bJYeakf1gGWM&vet=12ahUKEwiR9a654JaCAxUou5UCHcn2AbUQMygFegQIARBv..i&imgrefurl=https%3A%2F%2Fcriticalhits.com.br%2Fanime%2Ftenten-conseguiria-derrotar-a-sakura-em-naruto%2F&docid=L3dx_Hp9A0MmtM&w=1280&h=720&q=ten%20ten&hl=pt-BR&ved=2ahUKEwiR9a654JaCAxUou5UCHcn2AbUQMygFegQIARBv",
        "id": 11
    },
    {
        "nome": "Neji Hyuga",
        "clã": "Hyuga",
        "jutsu_especial": "Byakugan",
        "dano_especial": 1000,
        "natureza_de_chacra": "Água",
        "patente": "Jonin",
        "defesa": 900,
        "ataque": 950,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fwww.einerd.com.br%2Fwp-content%2Fuploads%2F2019%2F10%2FBoruto-encontro-Neji-capa-890x465.png&tbnid=-_6FEI7a_fIMxM&vet=12ahUKEwjS59jE4JaCAxV-hJUCHb-NC_EQMygEegQIARB3..i&imgrefurl=https%3A%2F%2Fwww.einerd.com.br%2Fboruto-neji-hyuga-manga%2F&docid=uwZW_gpEQVin5M&w=890&h=465&q=neji%20hyuga&hl=pt-BR&ved=2ahUKEwjS59jE4JaCAxV-hJUCHb-NC_EQMygEegQIARB3",
        "id": 12
    },
    {
        "nome": "Kiba Inuzuka",
        "clã": "Inuzuka",
        "jutsu_especial": "Fang Over Fang",
        "dano_especial": 980,
        "natureza_de_chacra": "Nenhum",
        "patente": "Chunin",
        "defesa": 870,
        "ataque": 980,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fstatic.wikia.nocookie.net%2Fnaruto%2Fimages%2Fb%2Fb1%2FKiba_%2528Parte_II%2529.png%2Frevision%2Flatest%3Fcb%3D20170530230546%26path-prefix%3Dpt-br&tbnid=3ke_ocvxZwDMFM&vet=12ahUKEwie3OLV4JaCAxVpu5UCHUvHBwAQMygBegQIARBF..i&imgrefurl=https%3A%2F%2Fnaruto.fandom.com%2Fpt-br%2Fwiki%2FKiba_Inuzuka&docid=ud4_SoZ9FHsVkM&w=1920&h=1080&q=kiba%20inuzuka%20shippuden&hl=pt-BR&ved=2ahUKEwie3OLV4JaCAxVpu5UCHUvHBwAQMygBegQIARBF",
        "id": 13
    },
    {
        "nome": "Shino Aburame",
        "clã": "Aburame",
        "jutsu_especial": "Parasitic Insects",
        "dano_especial": 960,
        "natureza_de_chacra": "Nenhum",
        "patente": "Jonin",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/imgres?imgurl=http%3A%2F%2F2.bp.blogspot.com%2F-vgBRNC97qtM%2FTifDK4di5vI%2FAAAAAAAAAgg%2Fowo345z_b-0%2Fs1600%2FShino-Aburame-shino-aburame-17766089-1280-720.jpg&tbnid=M3rVIraYgaHQYM&vet=12ahUKEwju36Dm4JaCAxWHTbgEHYggBcUQMygIegQIARB-..i&imgrefurl=http%3A%2F%2Fclubenarutoblogspostcom.blogspot.com%2F2011%2F07%2Faburame-shino.html&docid=neD3mo8y3o86xM&w=1280&h=720&q=shino%20aburame&hl=pt-BR&ved=2ahUKEwju36Dm4JaCAxWHTbgEHYggBcUQMygIegQIARB-",
        "id": 14
    },
    {
        "nome": "itachi uchiha",
        "clã": "Uchiha",
        "jutsu_especial": "Amaterasu",
        "dano_especial": 960,
        "natureza_de_chacra": "fogo",
        "patente": "Jonin",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fstatic.wikia.nocookie.net%2Fnaruto%2Fimages%2F2%2F24%2FItachi-Uchiha.png%2Frevision%2Flatest%3Fcb%3D20181104200812%26path-prefix%3Dpt-br&tbnid=NyMu1FFVscL4YM&vet=12ahUKEwji0OST4ZaCAxVrjZUCHedmC3sQMygAegQIARBv..i&imgrefurl=https%3A%2F%2Fnaruto.fandom.com%2Fpt-br%2Fwiki%2FItachi_Uchiha&docid=4OnH-8wpQwKpOM&w=1402&h=1061&q=itachi%20uchiha&hl=pt-BR&ved=2ahUKEwji0OST4ZaCAxVrjZUCHedmC3sQMygAegQIARBv",
        "id": 15
    },
    {
        "nome": "Kisame Hoshigaki",
        "clã": "Hoshigaki",
        "jutsu_especial": "Suiton Senshokukō",
        "dano_especial": 960,
        "natureza_de_chacra": "água",
        "patente": "Jonin",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fimages3.alphacoders.com%2F665%2F665366.jpg&tbnid=AlTzYXdkW17cDM&vet=12ahUKEwiU-9Tk4paCAxUtipUCHUARDQIQMygEegQIARB3..i&imgrefurl=https%3A%2F%2Fwall.alphacoders.com%2Ftag%2Fkisame-hoshigaki-wallpapers%3Flang%3DPortuguese&docid=yu6Fw91IwyZQQM&w=2560&h=1600&q=kisame%20&hl=pt-BR&ved=2ahUKEwiU-9Tk4paCAxUtipUCHUARDQIQMygEegQIARB3",
        "id": 16
    },
    {
        "nome": "Orochimaru",
        "clã": "konoha",
        "jutsu_especial": "Nan no Kaizou",
        "dano_especial": 960,
        "natureza_de_chacra": "terra",
        "patente": "sannin",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://br.images.search.yahoo.com/images/view;_ylt=AwrEb9uE8kNlls4AxWD16Qt.;_ylu=c2VjA3NyBHNsawNpbWcEb2lkAzhlZmE2ZTZhNzZiOGJjZjFjY2QzMTExYWYzNzY1ZTE3BGdwb3MDMwRpdANiaW5n?back=https%3A%2F%2Fbr.images.search.yahoo.com%2Fsearch%2Fimages%3Fp%3Dimagem%2Borochimaru%26type%3DE210BR91199G0%26fr%3Dmcafee%26fr2%3Dpiv-web%26tab%3Dorganic%26ri%3D3&w=1920&h=1080&imgurl=wallpapercave.com%2Fwp%2Fwp8788765.png&rurl=https%3A%2F%2Fwallpapercave.com%2Fnaruto-orochimaru-wallpapers&size=1136.8KB&p=imagem+orochimaru&oid=8efa6e6a76b8bcf1ccd3111af3765e17&fr2=piv-web&fr=mcafee&tt=Naruto+Orochimaru+Wallpapers+-+Wallpaper+Cave&b=0&ni=21&no=3&ts=&tab=organic&sigr=fVdoD4qOrjxn&sigb=QKC3w8IxScnc&sigi=xJttiWdBx.w8&sigt=aRedwrfYbS5L&.crumb=6tmUIL63NNq&fr=mcafee&fr2=piv-web&type=E210BR91199G0",
        "id": 17
    },
    {
        "nome": "tsunade",
        "clã": "senju",
        "jutsu_especial": "tecnica das 100 forças",
        "dano_especial": 960,
        "natureza_de_chacra": "terra",
        "patente": "sannin",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://br.images.search.yahoo.com/images/view;_ylt=AwrFNyno9ENlFu4API716Qt.;_ylu=c2VjA3NyBHNsawNpbWcEb2lkA2FlZjE4MzVlYTlhYzAwZTMwMTdlMzk4N2ZiY2Y0Y2E1BGdwb3MDOTAEaXQDYmluZw--?back=https%3A%2F%2Fbr.images.search.yahoo.com%2Fsearch%2Fimages%3Fp%3Dtsunade%26ei%3DUTF-8%26type%3DE210BR91199G0%26fr%3Dmcafee%26fr2%3Dp%253As%252Cv%253Ai%252Cm%253Asb-top%26nost%3D1%26tab%3Dorganic%26ri%3D90&w=1920&h=1080&imgurl=images8.alphacoders.com%2F945%2F945990.png&rurl=https%3A%2F%2Fwall.alphacoders.com%2Fbig.php%3Fi%3D945990&size=969.9KB&p=tsunade&oid=aef1835ea9ac00e3017e3987fbcf4ca5&fr2=p%3As%2Cv%3Ai%2Cm%3Asb-top&fr=mcafee&tt=Tsunade+Wallpaper+HD+by+Wallpuden&b=61&ni=140&no=90&ts=&tab=organic&sigr=cOeuG9yQKbtP&sigb=PTDP2OQu3kiz&sigi=WMDe_CMxXFTK&sigt=qeVxQZn1tYP8&.crumb=6tmUIL63NNq&fr=mcafee&fr2=p%3As%2Cv%3Ai%2Cm%3Asb-top&type=E210BR91199G0",
        "id": 18
    },
    {
        "nome": "Hashirama",
        "clã": "senju",
        "jutsu_especial": "kekkaijutsu",
        "dano_especial": 960,
        "natureza_de_chacra": "terra",
        "patente": "hokague",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fstatic.wikia.nocookie.net%2Fnaruto%2Fimages%2Fb%2Fb0%2FShodai_Tsuchi_-_Sugest%25C3%25A3o_do_Rafael_-_II.jpg%2Frevision%2Flatest%3Fcb%3D20141106201823%26path-prefix%3Dpt-br&tbnid=3fWNreE5gpAy8M&vet=12ahUKEwj_1szsg6aCAxVsu5UCHW32CiMQMygAegQIARA8..i&imgrefurl=https%3A%2F%2Fnaruto.fandom.com%2Fpt-br%2Fwiki%2FHashirama_Senju&docid=K87usCU9WGG5IM&w=960&h=540&q=primeiro%20hokage%20naruto&authuser=1&ved=2ahUKEwj_1szsg6aCAxVsu5UCHW32CiMQMygAegQIARA8",
        "id": 19
    },
    {
        "nome": "tobirama",
        "clã": "senju",
        "jutsu_especial": "Hiraishin no Jutsu",
        "dano_especial": 960,
        "natureza_de_chacra": "água",
        "patente": "hokague",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fstatic.wikia.nocookie.net%2Fnaruto%2Fimages%2Fc%2Fc0%2FTobirama_Senju_%2528HD%2529.png%2Frevision%2Flatest%3Fcb%3D20160220124906%26path-prefix%3Dpt-br&tbnid=pvUgXS11TC3m8M&vet=12ahUKEwjQqdzbhKaCAxV-hJUCHZdrBggQMygAegQIARBj..i&imgrefurl=https%3A%2F%2Fnaruto.fandom.com%2Fpt-br%2Fwiki%2FTobirama_Senju&docid=SWKPXUp3ZUroAM&w=1440&h=1080&q=segundo%20hokage&authuser=1&ved=2ahUKEwjQqdzbhKaCAxV-hJUCHZdrBggQMygAegQIARBj",
        "id": 20
    },
    {
        "nome": "Hiruzen",
        "clã": "sarutobi",
        "jutsu_especial": "celo do ceifeiro da morte",
        "dano_especial": 960,
        "natureza_de_chacra": "terra",
        "patente": "hokague",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/url?sa=i&url=https%3A%2F%2Fnaruto.fandom.com%2Fpt-br%2Fwiki%2FHiruzen_Sarutobi&psig=AOvVaw39WR0mxeDK0c1iAP-_mRC7&ust=1699039983120000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCPiAwbKHpoIDFQAAAAAdAAAAABAE",
        "id": 21
    },
    {
        "nome": "minato",
        "clã": "namikaze",
        "jutsu_especial": "Shiki Fuujin",
        "dano_especial": 960,
        "natureza_de_chacra": "vento",
        "patente": "hokague",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/url?sa=i&url=https%3A%2F%2Fnaruto.fandom.com%2Fpt-br%2Fwiki%2FMinato_Namikaze&psig=AOvVaw3yhvtuC_lDEF-vbxxtfAtj&ust=1699040074376000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJDQwdKHpoIDFQAAAAAdAAAAABAE",
        "id": 22
    },
    {
        "nome": "nagato",
        "clã": "Akatsuki",
        "jutsu_especial": "Técnica de Transferência de Forma",
        "dano_especial": 960,
        "natureza_de_chacra": "água",
        "patente": "gennin",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fstatic.wikia.nocookie.net%2Fnaruto%2Fimages%2Fb%2Fbb%2FNagato-Edo.PNG%2Frevision%2Flatest%3Fcb%3D20141014222811%26path-prefix%3Dpt-br&tbnid=LErsFVa4BZmSfM&vet=12ahUKEwjcju-4i6aCAxWYq5UCHckIBvUQMygAegQIARBP..i&imgrefurl=https%3A%2F%2Fnaruto.fandom.com%2Fpt-br%2Fwiki%2FNagato&docid=hFFi1cyYmYSymM&w=1020&h=580&q=nagato%20naruto&authuser=1&ved=2ahUKEwjcju-4i6aCAxWYq5UCHckIBvUQMygAegQIARBP",
        "id": 23
    },
    {
        "nome": "pain",
        "clã": "Akatsuki",
        "jutsu_especial": "shinra tensei",
        "dano_especial": 960,
        "natureza_de_chacra": "vento",
        "patente": "gennin",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fsm.ign.com%2Fign_br%2Fscreenshot%2Fdefault%2Fnaruto-yahiko_4ntj.jpg&tbnid=dG6Wu9gUxEH_gM&vet=12ahUKEwjVgIuljKaCAxWhSLgEHd40DDkQMygDegQIARBK..i&imgrefurl=https%3A%2F%2Fbr.ign.com%2Fnaruto-shippuden%2F87673%2Ffeature%2Fquiz-de-naruto-qual-caminho-de-pain-voce-e&docid=YGptYPip9nAC0M&w=1024&h=576&q=pain%20naruto%20jutsu&hl=pt-BR&authuser=1&ved=2ahUKEwjVgIuljKaCAxWhSLgEHd40DDkQMygDegQIARBK",
        "id": 24
    },
    {
        "nome": "konan",
        "clã": "Akatsuki",
        "jutsu_especial": "Dança do Shikigami",
        "dano_especial": 960,
        "natureza_de_chacra": "água",
        "patente": "gennin",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/imgres?imgurl=http%3A%2F%2Fpm1.aminoapps.com%2F6512%2F55d464e5d5ced2ac66d9e800c5ff4ebb4622c380_00.jpg&tbnid=Wc-y5_NkvounxM&vet=12ahUKEwjQ04DQjqaCAxWPSrgEHSSYCB4QMygOegUIARCJAQ..i&imgrefurl=https%3A%2F%2Faminoapps.com%2Fc%2Fnaruto-shippuden-online%2Fpage%2Fitem%2Fkonan-60%2FKnMl_npUKIPNB6pMDKPKjPBKe1a8rlXR4&docid=70707Pjb7pwM5M&w=512&h=408&q=konan%20&hl=pt-BR&authuser=1&ved=2ahUKEwjQ04DQjqaCAxWPSrgEHSSYCB4QMygOegUIARCJAQ",
        "id": 25
    },
    {
        "nome": "sasori",
        "clã": "Akatsuki",
        "jutsu_especial": "Performance das Cem Marionetes",
        "dano_especial": 960,
        "natureza_de_chacra": "terra",
        "patente": "gennin",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fstatic.wikia.nocookie.net%2Fnaruto%2Fimages%2F7%2F7b%2FSasori_%2528Parte_II%2529.PNG%2Frevision%2Flatest%3Fcb%3D20141202202433%26path-prefix%3Dpt-br&tbnid=3uAUqR2D27INeM&vet=12ahUKEwj26eC1kKaCAxWKVrgEHexSAi0QMygBegQIARBu..i&imgrefurl=https%3A%2F%2Fnaruto.fandom.com%2Fpt-br%2Fwiki%2FSasori&docid=2ER8rNedFOVmkM&w=1360&h=768&q=sasori&hl=pt-BR&authuser=1&ved=2ahUKEwj26eC1kKaCAxWKVrgEHexSAi0QMygBegQIARBu",
        "id": 26
    },
    {
        "nome": "deidara",
        "clã": "Akatsuki",
        "jutsu_especial": "Argila Explosiva",
        "dano_especial": 960,
        "natureza_de_chacra": "terra",
        "patente": "gennin",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fs.aficionados.com.br%2Fimagens%2Fdeidara-1_cke.jpg&tbnid=NW20HVx008sPzM&vet=12ahUKEwiw09HfkaaCAxVrS7gEHfT-CvAQMygDegQIARBy..i&imgrefurl=https%3A%2F%2Fwww.aficionados.com.br%2Fdeidara-historia-jutsus-trajetoria-akatsuki%2F&docid=-8r_Lp8QTQvX_M&w=600&h=348&q=deidara&hl=pt-BR&authuser=1&ved=2ahUKEwiw09HfkaaCAxVrS7gEHfT-CvAQMygDegQIARBy",
        "id": 27
    },
    {
        "nome": "hidan",
        "clã": "Akatsuki",
        "jutsu_especial": "Jashin",
        "dano_especial": 960,
        "natureza_de_chacra": "água",
        "patente": "gennin",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fkanto.legiaodosherois.com.br%2Fw760-h398-gnw-cfill-q95%2Fwp-content%2Fuploads%2F2021%2F11%2Flegiao_8BmVpt9YDWa_.jpg.webp&tbnid=DCo_XU-0wIy9TM&vet=12ahUKEwjjsKCrkqaCAxWLnJUCHa_aDZsQMygCegQIARBw..i&imgrefurl=https%3A%2F%2Fwww.legiaodosherois.com.br%2F2021%2Fhidan-motivo-imortal-naruto.html&docid=zJzsOnjOWb0A1M&w=760&h=398&q=hidan&hl=pt-BR&authuser=1&ved=2ahUKEwjjsKCrkqaCAxWLnJUCHa_aDZsQMygCegQIARBw",
        "id": 28
    },
    {
        "nome": "kakuzo",
        "clã": "Akatsuki",
        "jutsu_especial": "Terror da Terra Rancorosa",
        "dano_especial": 960,
        "natureza_de_chacra": "vento",
        "patente": "gennin",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fkanto.legiaodosherois.com.br%2Fw728-h381-gnw-cfill-gcc%2Fwp-content%2Fuploads%2F2022%2F11%2Flegiao_9fWE5bOyV82J.jpg.webp&tbnid=1GY9x3h2fYHtVM&vet=12ahUKEwj-94rykqaCAxWNUbgEHdyyAyYQMygCegQIARBw..i&imgrefurl=https%3A%2F%2Fwww.legiaodosherois.com.br%2F2022%2Fkakuzu-historia-origem-poderes-naruto.html&docid=oNbeucFGhHI6WM&w=728&h=381&q=kakuzu&hl=pt-BR&authuser=1&ved=2ahUKEwj-94rykqaCAxWNUbgEHdyyAyYQMygCegQIARBw",
        "id": 29
    },
    {
        "nome": "Killer B",
        "clã": "Kumogakure",
        "jutsu_especial": "Dança das Sete Espadas",
        "dano_especial": 960,
        "natureza_de_chacra": "terra",
        "patente": "gennin",
        "defesa": 920,
        "ataque": 890,
        "imagem": "https://www.google.com.br/imgres?imgurl=https%3A%2F%2Fassetsio.reedpopcdn.com%2F-1455107475249.jpg%3Fwidth%3D1600%26height%3D900%26fit%3Dcrop%26quality%3D100%26format%3Dpng%26enable%3Dupscale%26auto%3Dwebp&tbnid=y5xgDbiLPh4sBM&vet=12ahUKEwjCtNW4lKaCAxUfTLgEHY_DAmEQMygFegQIARB2..i&imgrefurl=https%3A%2F%2Fwww.eurogamer.pt%2Fvideo-jogamos-com-raikage-e-killer-bee-em-naruto-ultimate-ninja-storm-4&docid=Q52QuCCSybo7DM&w=1600&h=900&q=killer%20bee&hl=pt-BR&authuser=1&ved=2ahUKEwjCtNW4lKaCAxUfTLgEHY_DAmEQMygFegQIARB2",
        "id": 30
    },

]



export default Api;
